
services:
  db:
    image: postgres:18
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
       - "5432:5432"
    volumes:
      - event_processing_db_data:/var/lib/postgresql
    deploy:
      resources:
        limits:
          cpus: "1.0"     # give it one full CPU core
          memory: 1G      # give it 1GB of RAM

  kafka:
    image: apache/kafka:4.2.0
    environment:
      KAFKA_KRAFT_MODE: 'true'

      KAFKA_NODE_ID: 1 
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'

      KAFKA_PROCESS_ROLES: 'broker,controller' 
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093' 
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1   

      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093' 
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER' 
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'

      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/var/lib/kafka/data


volumes:
  event_processing_db_data:
  kafka_data: